### PR TITLE
Add modulesync

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by danzilio** [comment]
Is ModuleSync (and now that I think about it, ghostbuster) really a tool or a plugin? I think these may be tools in their own right (though it would be helpful to define these things in the README). How about:

Tool - can run independently
Plugin - adds functionality to a tool

Thoughts?

**Comment by danzilio** [comment]
I added some more info to the README in #5. Let me know what you think!

**Comment by danzilio** [comment]
I'm going to close this in favor of #8. I'm also going to submit a PR to make ghostbuster it's own tool.

**Comment by raphink** [comment]
OK, good for me :-)

**Comment by DavidS** [comment]
@raphink sorry, I didn't check for existing work when I submitted #8 :-)

**Comment by raphink** [comment]
No problem @DavidS. That wasn't too much code anyway ;-)

**Pull request closed without merging**
